### ISSUE TITLE
Staking working unconsitently

### ISSUE THREAD

**Issue by Mathiasb17** [tokenpay/tokenpay#12]
Hello,

I'm not sure if this is the right place to post so sorry if it's not, could not get any valuable help on telegram or discord...

I've been successfully staking for one month, have had several rewards periodically. I haven't had any reward for the last month and a half with several thousands coins (i should have one every 2 days or so according to the calculator). 

I tried to fix it with the online tutorial : https://www.youtube.com/watch?v=bTRU7pskXn8

I did it twice, then waiting 1 week, it did not change anything, still no rewards.

Besides my wallet displays a total balance of 0.00 while my staking weight fits my number of coins.

Staking seems working for some people, reading telegram. But for many other it's not, apparently. I guess there is some kind of problem that should be digged, do you have any idea ?

I'm running the wallet on a raspberry pi 3b+.

**Comment by Mathiasb17** [comment]
Hello,

So yesterday i did the installation procedure all over again, waited for the wallet to sync for a few hours.

After it synced i received a reward in about 10 min, so i guess i'm good to go.

I'll leave this open anyways because there seems to be a known issue about this.

**Comment by ArtCenter1** [comment]
As far as I know the inconsistency of balance usually have something to do with syncing. Because of the nature of PoS a lot of redundant blocks were generated. That's why you see a lot of orphan blocks and unaccepted rewards.  Maybe that plays some part in the syncing delay....

**Comment by justinvforvendetta** [comment]
i haven't seen anyone else have this issue
