### ISSUE TITLE
make install fails due to leveldb submodule

### ISSUE THREAD

**Issue by gabriel-samfira** [tokenpay/tokenpay#2]
Running make install on this project will fail due to the fact that the ```Makefile``` that gets generated, will run ```make install``` for each submodule that is included in this project. The problem is that the ```leveldb``` submodule does not have an install target. To work around it, you can simply add an empty ```install:``` stanza to the leveldb makefile.

**Comment by Mathiasb17** [comment]
Hello ! I still have this problem problem on master, is that normal ?
